name: generate_pdf_file
on: push
jobs:
  sprawozdanie:
    runs-on: ubuntu-24.04
    steps: 
      - run: sudo apt-get install texlive-xetex inkscape pandoc 
      - uses: actions/checkout@v4 
      - run: pip install numpy pint open-atmos-jupyter-utils scipy nbconvert ipykernel 
      - run: python -m nbconvert --to pdf --execute Lab1.ipynb 
      - uses: actions/upload-artifact@v4
        with:
          path: sprawozdanie.pdf
  

